added SIMPLE to LQ list 0-100 no modifiers, no other info shown
emuflight/EmuFlight pull request #396
Opened 2020-10-22 23:21 UTC by Kaiowarez

Thank you for contributing to EmuFlight!

## Important considerations when opening a pull request:

1. Pull requests will only be accepted if they are opened against the `master` branch. Pull requests opened against other branches without prior consent from the maintainers will be closed;

2. Please follow the coding style guidlines: https://github.com/emuflight/EmuFlight/blob/master/docs/development/CodingStyle.md

3. Keep your pull requests as small and concise as possible. One pull request should only ever add / update one feature. If the change that you are proposing has a wider scope, consider splitting it over multiple pull requests. In particular, pull requests that combine changes to features and one or more new targets are not acceptable.

4. Ideally, a pull request should contain only one commit, with a descriptive message. If your changes use more than one commit, rebase / squash them into one commit before submitting a pull request. If you need to amend your pull request, make sure that the additional commit has a descriptive message, or - even better - use `git commit --amend` to amend your original commit.

5. All pull requests are reviewed. Be ready to receive constructive criticism, and to learn and improve your coding style. Also, be ready to clarify anything that isn't already sufficiently explained in the code and text of the pull request, and to defend your ideas.

6. If your pull request is a fix for one or more issues that are open in GitHub, add a comment to your pull request, and add the issue numbers of the issues that are fixed in the form `Fixes #<issue number>`. This will cause the issues to be closed when the pull request is merged;

7. Remove this Text :).

## Any questions?

Please join our discord server:
https://discord.gg/gdP9CwE

2020-11-12 19:09 UTC, nerdCopter requested changes
* i think we should remove case TBS, and let it fall-though to default. i.e. no reason to have duplicate code, and results the same.
* optionally scale 0-100 to 170-300 as discussed. `osdLQfinal = scaleRangef(osdLQ, 0, 100, 170, 300);`, AFAIK.

2020-11-12 20:40 UTC, Kaiowarez commented
Could make tbs default, then scaled, mode, freq, simple?

On Thu, Nov 12, 2020, 2:09 PM nerdCopter <notifications@github.com> wrote:

> *@nerdCopter* requested changes on this pull request.
>
>    - i think we should remove case TBS, and let it fall-though to
>    default. i.e. no reason to have duplicate code, and results the same.
>    - optionally scale 0-100 to 170-300 as discussed. osdLQfinal =
>    scaleRangef(osdLQ, 0, 100, 170, 300);, AFAIK.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/emuflight/EmuFlight/pull/396#pullrequestreview-529406104>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOMD72DJEJYZ3UC3UQSI3OLSPQXF7ANCNFSM4S323WXA>
> .
>

2020-11-21 03:20 UTC, nerdCopter reviewed
@Kaiowarez , can you scout and find out if Tracer "just works" and if we need mode 4 "250hz" text?

2020-11-21 20:06 UTC, nerdCopter approved these changes

2020-11-23 13:57 UTC, merged