add target iflight f745 aio
emuflight/EmuFlight pull request #668
Opened 2021-08-08 04:32 UTC by Kaiowarez

Thank you for contributing to EmuFlight!

## Important considerations when opening a pull request:

1. Pull requests will only be accepted if they are opened against the `master` branch. Pull requests opened against other branches without prior consent from the maintainers will be closed;

2. Please follow the coding style guidlines: https://github.com/emuflight/EmuFlight/blob/master/docs/development/CodingStyle.md

3. Keep your pull requests as small and concise as possible. One pull request should only ever add / update one feature. If the change that you are proposing has a wider scope, consider splitting it over multiple pull requests. In particular, pull requests that combine changes to features and one or more new targets are not acceptable.

4. Ideally, a pull request should contain only one commit, with a descriptive message. If your changes use more than one commit, rebase / squash them into one commit before submitting a pull request. If you need to amend your pull request, make sure that the additional commit has a descriptive message, or - even better - use `git commit --amend` to amend your original commit.

5. All pull requests are reviewed. Be ready to receive constructive criticism, and to learn and improve your coding style. Also, be ready to clarify anything that isn't already sufficiently explained in the code and text of the pull request, and to defend your ideas.

6. If your pull request is a fix for one or more issues that are open in GitHub, add a comment to your pull request, and add the issue numbers of the issues that are fixed in the form `Fixes #<issue number>`. This will cause the issues to be closed when the pull request is merged;

7. Remove this Text :).

## Any questions?

Please join our discord server:
https://discord.gg/gdP9CwE

2021-08-08 14:26 UTC, frizzle101101 reviewed
not sure but dont think the betaflightf4 change is to be included...

2021-08-08 20:16 UTC, nerdCopter commented
can't accept this with Betaflight target modded in same branch

2021-08-09 05:02 UTC, frizzle101101 requested changes
i think you are missing #define USE_LED_STRIP

2021-08-09 23:31 UTC, frizzle101101 commented
> i think you are missing #define USE_LED_STRIP, if that is realted to @Mcrubens comment on #479

i realize the led pin was not broken out on the v1 but on the v1.2 it is, so please add 
`#define USE_LED_STRIP
#define WS2811_PIN                      PD12`

also id sugest removing/disabling/comenting out, the unused/not-broken-out uarts like UART_8, UART_6, UART_5, only 1,2,4 and 7 are broken out

2021-08-12 01:07 UTC, frizzle101101 commented
I hope this helps with your next target adds, i sure learned somthing about Legacy targets lol

2021-08-12 14:27 UTC, nerdCopter commented
Thank you @frizzle101101 !

@Kaiowarez , there is multiple comments(info) that needs attention above, thank you good sir!

2021-08-19 23:02 UTC, frizzle101101 reviewed
here you go these are clear instructions to get this done asap by anyone who can read

2021-08-19 23:02 UTC, frizzle101101 commented on src/main/target/BETAFLIGHTF4/target.h
> +#define I2C_DEVICE              (I2CDEV_1)
remove changes

2021-08-19 23:02 UTC, frizzle101101 commented on src/main/target/BETAFLIGHTF4/target.h
> -
remove changes

2021-08-20 12:36 UTC, nerdCopter commented
* thank you @frizzle101101 .  i will take a look and attempt this.
* yesterday i made a new PR with both your and kaio's authorship in my commits.  
* i will see about adding these things to #682 .
* regarding DPS310, @JulioCesarMatias was adding DPS310 in PR #578 , but the testers stopped responding.

2021-08-21 18:24 UTC, nerdCopter commented
Superseded by #686

2021-08-21 18:24 UTC, closed without merging