multiple targets fix USE_LED_STRIP
emuflight/EmuFlight pull request #855
Opened 2022-08-08 15:46 UTC by nerdCopter

* multiple targets fix `#define USE_LED_STRIP` (was wrongly `USE_LEDSTRIP`)

2022-08-08 15:55 UTC, Kaiowarez commented
Looks good

2022-08-08 16:03 UTC, Kaiowarez approved these changes

2022-08-08 22:52 UTC, Quick-Flash approved these changes
good catch

2022-08-09 00:55 UTC, BeauBrewski requested changes
AIRBOTF7HDV:
TYPO: #define USE_LEDS_TRIP
Needs to be #define USE_LED_STRIP

2022-08-09 14:11 UTC, nerdCopter commented
may need to add `#define USE_LED_STRIP` to `SKYSTARSF7HD`, waiting for opinion.

2022-08-09 16:21 UTC, BeauBrewski approved these changes

2022-08-09 16:22 UTC, merged